/**
 * Every tunable number in one place, serialisable, and fed straight to the debug
 * UI. Distances are metres, angles degrees, probabilities [0, 1].
 */

/**
 * Roof colour families. Declared here rather than beside the palettes because
 * the mix between them is a setting, and `material/` already depends on `core/`
 * — the other direction would be a cycle.
 */
export type RoofHue = 'redBrown' | 'navy' | 'grey' | 'brown' | 'green';
export type RoofHueMix = Record<RoofHue, number>;

/**
 * How the street network is laid out. Both are the same generator — Tier-1
 * roads cut the town into districts, each district grids itself — differing
 * only in how much the districts are allowed to disagree with each other.
 *
 * `district` is the default: several districts at visibly different angles,
 * with dead ends and staggered junctions. An organically grown suburb, where
 * each development was fitted to the land it replaced.
 * `grid` is the planned 区画整理 alternative — one dominant orientation,
 * nothing deleted, nothing dead-ending, and a pair of diagonal through-roads.
 */
export type RoadLayout = 'district' | 'grid';

/**
 * Declared here rather than beside the road generator because `perimeterClass`
 * is a setting, and `city/` already depends on `core/` — the other direction
 * would be a cycle. `city/Roads.ts` re-exports it as the canonical name.
 */
export type RoadClass = 'arterial' | 'collector' | 'local' | 'private';

/**
 * 用途地域 — the use zone a *district* is designated as.
 *
 * Declared here for the same reason as `RoadClass`: the mix is a setting, and
 * `city/` already depends on `core/`. Keeping it here also lets `District`
 * carry its own zone without `RoadDistricts` importing the assignment.
 *
 * The distinction this type draws is the one Japanese planning already draws,
 * and the reason it is worth keeping in the type system: **用途地域 is the map**
 * — decided upstream, per district, before a single lot exists — while
 * `LotKind` is **what actually got built**, decided per lot from the geometry
 * the map made possible. A zone never places a building. It only says which
 * ones the geometric gates are allowed to consider.
 */
export type UseZone =
  | 'lowRise' // 第一種低層住居専用地域
  | 'midRise' // 第一種中高層住居専用地域・住居地域
  | 'neighbourCom' // 近隣商業地域
  | 'commercial' // 商業地域（駅前）
  | 'quasiIndust' // 準工業地域
  | 'industrial'; // 工業地域

export interface LandUseParams {
  /** Radius over which the station's pull on 商業地域 falls off, metres. */
  commercialCoreRadius: number;
  /** How far 近隣商業 may reach from the station along a wide road, metres. */
  neighbourhoodRadius: number;
  /**
   * Ceiling on the combined area of 商業 and 近隣商業, as a share of the town.
   *
   * A radius alone does not bound it. The town shrinks but the districts do not
   * shrink with it, so at `extent: 190` the shops reached most of the map and a
   * quarter of every lot came out a 店舗併用住宅. Shops are a share of a town, not
   * a distance from its station.
   */
  commercialShare: number;
  /** Target share of the town area given over to 工業地域, [0, 1]. */
  industrialShare: number;
  /** No industrial district may come closer than this to the station, metres. */
  industrialMinStationDist: number;
  /** Ring 準工業 around the industrial belt, so a factory never abuts 低層住専. */
  quasiIndustrialRing: boolean;
  /** How much Tier-1 frontage counts toward being commercial, relative to the station. */
  arterialFrontageWeight: number;
  noiseScale: number;
  noiseWeight: number;
}

/**
 * The river. One river, running right across the town — deliberately not a pond
 * and deliberately not a tributary network.
 *
 * `geom/boolean.ts` drops holes, and a body of water that closes inside a single
 * block *is* a hole: it would be silently swallowed and a house would be built
 * on it. A river that crosses the town splits every block it touches into two,
 * which the boolean pipeline handles correctly.
 */
export interface RiverParams {
  enabled: boolean;
  /** Width of the water surface, metres. */
  width: number;
  /** How far from the centreline the valley carve reaches. */
  valleyWidth: number;
  /**
   * Minimum downstream fall, as a fraction. The bed profile is forced monotone
   * with at least this gradient: a river that runs uphill is the single most
   * obvious way to break the illusion, and an fBm field will happily produce one
   * if the carve is a plain subtraction.
   */
  bedGrade: number;
  /** Water surface above the bed. */
  waterDepth: number;
  /** Extra width beyond the water that nothing may be built on. */
  bankMargin: number;
  /** Lateral wander of the centreline, metres. */
  meander: number;
}

/**
 * 段丘崖 — the terrace scarps.
 *
 * Generated by offsetting the river centreline sideways, because that is what a
 * 河岸段丘 is: the abandoned floors of the same valley. Terraces placed
 * independently of the river read as random walls.
 */
export interface TerraceParams {
  count: number;
  /** Height of one scarp, metres. */
  step: number;
  stepVariation: number;
  /**
   * Width of the scarp band, metres.
   *
   * Kept at one grid cell. A step of 4 m over a band of 4 m is 45° — unwalkable,
   * undrivable, and it forces a 擁壁 on every lot along it, which is the point.
   * Anything narrower is destroyed by the bilinear sampler anyway, so a narrower
   * band would only be a lie.
   */
  width: number;
  /** Lateral offset from the river, as a fraction of the town half-extent. */
  minOffset: number;
  maxOffset: number;
}

/**
 * The land the town is built on.
 *
 * Everything here is in absolute metres and deliberately *not* scaled by
 * `roads.extent`. The tests run a 190 m town and the shipped one is 320 m; if
 * the hills scaled with the town, the tested landscape would not be the shipped
 * landscape and the suite would stop testing what actually ships.
 */
export interface TerrainParams {
  enabled: boolean;
  /** Heightfield sample pitch, metres. */
  cell: number;
  /** How far the field extends beyond the town square, metres. */
  margin: number;
  /** Peak-to-trough relief of the hills, metres. */
  relief: number;
  hillScale: number;
  hillOctaves: number;
  /**
   * Overall fall across the town, as a fraction. Without it the fBm reads as
   * random lumps rather than as a landform that water could drain off.
   */
  tiltGrade: number;
  /**
   * Ground steeper than this (as a tangent) carries no building.
   *
   * Generous on purpose — 0.8 is nearly 39°. A Japanese hill suburb is built on
   * ground far steeper than anything you could stand a house on unaided, and the
   * whole 造成 machinery in `city/Platform.ts` exists to make that work: the lot
   * is cut to a level pad and the 擁壁 holds the difference. Setting this to
   * something a *natural* slope could carry throws away most of the hillside and
   * leaves the walls with nothing to retain.
   */
  maxBuildSlope: number;
  river: RiverParams;
  terrace: TerraceParams;
}

/**
 * How the town grew.
 *
 * Nested inside `RoadParams` rather than sitting beside it: growth decides where
 * roads go, `ROAD_LAYOUT_PRESETS` has to be able to set it, and `generateRoads`
 * then needs no extra argument.
 */
export interface GrowthParams {
  enabled: boolean;
  /** The town's age. The one control this whole feature exists to expose. */
  steps: number;
  /**
   * The step at which the frontier reaches the edge of the town.
   *
   * This is what makes `steps` a *clock* rather than a second seed. The frontier
   * schedule has to be a function of the absolute step number, not of
   * `step / steps` — with the latter, raising the age changed the radius every
   * step aimed at, so the candidate set differed from step one and the whole
   * network came out unrecognisably different. An older town is supposed to be
   * the younger one with more added to it.
   *
   * A town with `steps` below this is caught mid-growth: smaller, with its
   * frontier still short of the perimeter. Above it, the extra steps go into
   * filling in what is already there.
   */
  fullAt: number;
  /**
   * How the frontier radius grows with step, as an exponent. Below 1 the town
   * spreads fast and then spends its later steps filling the core in — which is
   * what produces the density gradient the whole thing is for.
   */
  spreadExponent: number;
  streetsPerStep: number;
  candidatesPerStreet: number;
  /**
   * Plot size at the station and at the fringe, as a multiple of the zone's own
   * mean. The town's density gradient lives here — see `city/LotModule.ts`,
   * which sizes the street grid to whichever plot a district is getting.
   */
  coreLotScale: number;
  fringeLotScale: number;
  /** Steps between promoting a local chain to collector / a collector to arterial. */
  collectorInterval: number;
  arterialInterval: number;
  /** Steepest longitudinal gradient each class of road will accept, as a tangent. */
  maxGradient: Record<RoadClass, number>;
  maxBridgeSpan: number;
  /** A road may only bridge the river if it crosses it more squarely than this. */
  minRiverCrossAngle: number;
  /** Share of the newest generation's lots left undeveloped. */
  fringeVacancy: number;
  /** Gauss–Seidel sweeps in the road profile solver. Fixed, so it stays deterministic. */
  profileRelaxIterations: number;
  // --- Candidate cost weights ----------------------------------------------
  slopeWeight: number;
  cutFillWeight: number;
  crossSlopeWeight: number;
  spacingWeight: number;
  reachWeight: number;
  loopBonus: number;
  bridgeCost: number;
}

/**
 * 造成 — how a lot is levelled into the slope, and what holds the result up.
 *
 * Its own group rather than part of `buildings`, because none of it is a
 * property of the building: an empty lot on a slope still gets a platform and
 * still needs a wall.
 */
export interface PlatformParams {
  enabled: boolean;
  /** How far the pad sits above the street by default. Japanese lots are raised. */
  plinth: number;
  /**
   * Pad heights snap to a multiple of this — one stair riser.
   *
   * This is what makes a row of pads down a sloping street line up into a
   * staircase instead of a smooth ramp, and it is the whole visual signature of
   * 雛壇造成.
   */
  riserQuantum: number;
  maxRiseAboveStreet: number;
  maxCutBelowStreet: number;
  /** Height difference above which a boundary gets a wall rather than a batter. */
  wallMin: number;
  wallThickness: number;
  /** How far inside the boundary the wall stands. */
  wallInset: number;
  /** Run over rise of an earth batter. */
  batterSlope: number;
  stepRiser: number;
  /** Cut or fill at a road edge above which it is walled rather than battered. */
  roadWallMin: number;
}

export interface RoadParams {
  layout: RoadLayout;
  growth: GrowthParams;
  /** Straight through-roads cutting across the grid. Used by the `grid` layout. */
  diagonalCount: number;
  /** Half-extent of the generated town, metres. */
  extent: number;
  arterialCount: number;
  arterialWidth: number;
  collectorWidth: number;
  collectorSpacing: number;
  localWidth: number;
  /**
   * How much neighbouring blocks differ in *length*, as a fraction.
   *
   * Only along the street. A block's depth is two lot depths and is not
   * negotiable — varying it by ±18%, which is what this number used to do to
   * both axes at once, moved the block between 22 m and 40 m of usable depth
   * where the lots needed 27, and the subdivider then stretched or abandoned the
   * difference. Along the street the same variation is free: it changes how many
   * plots fit and nothing else, and it is what stops a district reading as
   * graph paper.
   */
  gridSpacingVariation: number;
  /** Fraction of street spans deleted outright. */
  deleteFraction: number;
  /** Fraction of terminal spans truncated into dead ends. */
  deadEndFraction: number;
  nodeSnap: number;
  minEdgeLength: number;

  // --- District layout ------------------------------------------------------
  /** One grain for the whole town: how far the base axis tilts off north, degrees. */
  townAxisJitter: number;
  /** Bends per Tier-1 road. A real 幹線道路 has two or three, not ninety. */
  tier1BendCount: number;
  /** Hard cap on a single Tier-1 bend, degrees. */
  tier1MaxBend: number;
  /** Two Tier-1 roads may never come closer than this except where they cross, metres. */
  tier1MinSpacing: number;
  /**
   * Junctions sharper than this are not built. Acute crossings are what produce
   * the overlapping asphalt and the sliver blocks that get discarded, so this
   * is a hard constraint on the skeleton rather than a preference.
   */
  minJunctionAngle: number;
  /** How far a district's grid may rotate off its dominant boundary road, degrees. */
  districtAxisJitter: number;
  /** Faces below this get no local grid and stay a single block, m². */
  minDistrictArea: number;
  /** Floor on a local grid gap, metres. */
  minLocalSpacing: number;
  /** Share of local street lines given a 食い違い offset. */
  staggerFraction: number;
  staggerDistance: number;
  /** Probability a local street bends once, at one of its junctions. */
  localBendChance: number;
  /**
   * Cap on that bend, degrees. The bend sits *on* a junction, so every block
   * edge stays straight and every lot along a run keeps one exact frontage
   * direction — the street reads as bent without the houses fanning out.
   */
  localBendAngle: number;
  /** Gap required between the ribbons of two roads that do not share a node, metres. */
  roadClearance: number;
  /**
   * Close the town square with a road. Effectively mandatory: `extractFaces`
   * discards the single clockwise outer cycle, so without a ring the outermost
   * region is not a face and there are no boundary districts at all.
   */
  perimeterRoad: boolean;
  perimeterClass: RoadClass;
  /** Assign the road hierarchy to the district's own grid lines. */
  promoteGridLines: boolean;
}

export interface LotParams {
  minLotArea: number;
  maxLotArea: number;
  /**
   * Cap for parcels with wide frontage on an arterial or collector. Those
   * parcels are consolidated in reality, and they are the only places a
   * マンション can physically go — so the zoning rules never have to name one.
   */
  maxLotAreaMajor: number;
  /** Lot width and depth are larger along wide roads. */
  widthMeanMajor: number;
  depthMeanMajor: number;
  /**
   * Minimum street frontage, metres. Japan's 接道義務 is 2 m, but this doubles
   * as the acceptance test for leftover scraps, and a suburb is full of parcels
   * that never had to satisfy it — 未接道 slivers between two developments, the
   * corner a road widening left behind. Kept below the legal figure so those
   * survive as ground rather than vanishing.
   */
  minFrontage: number;
  /**
   * Mean and spread of lot depth.
   *
   * The master dimension of the whole town, not a preference. `LotModule` spaces
   * the streets at two of these plus the road between them, so raising it does
   * not make the lots deeper within the same blocks — it makes the blocks
   * deeper. What it changes is the *proportion* of the plot, and through that
   * the proportion of the house: 12.8 against a 9.6 m frontage is a plot half
   * again as deep as it is wide, and a house a little less than that once the
   * setbacks and the parking space are taken off the front.
   */
  depthMean: number;
  depthSigma: number;
  depthMin: number;
  depthMax: number;
  /** Mean and spread of lot width along the street. */
  widthMean: number;
  widthSigma: number;
  widthMin: number;
  widthMax: number;
  /** Non-parallel side boundaries: sigma of the cut-direction jitter, degrees. */
  cutAngleJitter: number;
  /** A block core at least this large can be opened up with a private lane. */
  minCoreArea: number;
  /** A smaller core still supports flag lots reached by a pole. */
  flagLotMinCore: number;
  /** Width of a 私道 (designated private road). */
  privateLaneWidth: number;
  /** Width of a flag lot's pole (竿). */
  poleWidth: number;
  flagLotChance: number;
  /**
   * Parcels whose largest inscribed circle is smaller than this are discarded.
   * This, not `minLotArea`, is what actually rejects a scrap: a 3 m × 4 m corner
   * is 12 m² but only holds a 1.5 m circle. Lowering `minLotArea` without
   * lowering this changes nothing.
   */
  minInscribedRadius: number;
  /** Gutter allowance added to each road's half width. */
  gutterWidth: number;
  maxRecursionDepth: number;
}

export interface ZoningParams {
  stationRadius: number;
  arterialRadius: number;
  collectorRadius: number;
  noiseScale: number;
  noiseWeight: number;
  mansionMinArea: number;
  mansionMinFrontage: number;
  mansionMinUrbanity: number;
  apartMinArea: number;
  apartMinFrontage: number;
  apartUrbanityLo: number;
  apartUrbanityHi: number;
  /** Probability of cutting the flood fill when growing a 分譲地 cluster. */
  clusterCutChance: number;

  /** 店舗併用住宅: the 間口 range a shophouse row is cut into. */
  shophouseMinFrontage: number;
  shophouseMaxFrontage: number;
  /**
   * Urbanity at which a shop is worth opening on a street that is not a main
   * road. Being inside 近隣商業 is not enough on its own — the zone is a whole
   * district, and a 商店街 is a street.
   */
  shophouseMinUrbanity: number;
  zakkyoMinArea: number;
  zakkyoMinUrbanity: number;
  /** コンビニ: a wide, shallow parcel on a wide road, and one per district. */
  konbiniMinArea: number;
  konbiniMinFrontage: number;
  /** Ratio of depth to frontage above which a parcel is too deep for a forecourt. */
  konbiniMaxDepthRatio: number;
  konbiniPerDistrict: number;
  factoryMinArea: number;
  warehouseMinArea: number;
  /** Smallest circle an industrial shed needs to fit, radius in metres. */
  industrialMinRadius: number;
}

export interface BuildingParams {
  /** Half-ken module. Everything in a façade snaps to this. */
  module: number;
  frontSetback: number;
  sideSetback: number;
  rearSetback: number;
  /**
   * Depth of the parking space from the street boundary. The pad is a rectangle
   * in one front corner of the lot, *not* a band across the whole frontage —
   * setting the whole front elevation back by a car's length wasted about 17% of
   * a median lot, and the wider the frontage the more it wasted.
   */
  carPadDepth: number;
  /** Width of the parking space along the street. */
  carPadWidth: number;
  /**
   * Fraction of the buildable area a footprint aims to occupy, before the
   * archetype's notch and the lot clip take their share. Together with the
   * coverage limit this is what actually decides how much garden is left; the
   * 建ぺい率 alone does not, because the setbacks usually bind first.
   */
  footprintFill: number;
  houseCoverage: number;
  houseFar: number;
  houseHeightLimit: number;
  apartCoverage: number;
  apartFar: number;
  mansionCoverage: number;
  mansionFar: number;
  mansionHeightLimit: number;
  /** 北側斜線: base height and slope for low-rise and mid-rise zones. */
  northSlantBaseLow: number;
  northSlantBaseMid: number;
  northSlantSlope: number;
  /** 道路斜線 slope. */
  roadSlantSlope: number;
  floorHeightHouse: number;
  floorHeightApart: number;
  floorHeightMansion: number;
  /** 店舗併用住宅 and コンビニ: a shop storey is taller than a living one. */
  floorHeightShop: number;
  /** 雑居ビル: one tenant per floor. */
  floorHeightTenant: number;
  /**
   * A factory bay is one storey but the height of three. `mass.ts` skips the
   * 斜線 cut entirely below two floors, so a tall single storey is never sliced.
   */
  floorHeightFactory: number;
  floorHeightWarehouse: number;
  /** 店舗併用住宅: 建ぺい率 and 容積率 on a 近隣商業 parcel. */
  shopCoverage: number;
  shopFar: number;
  zakkyoCoverage: number;
  zakkyoFar: number;
  zakkyoHeightLimit: number;
  /** A コンビニ covers little of its plot; most of it is the car park. */
  konbiniCoverage: number;
  industrialCoverage: number;
  industrialFar: number;
  industrialHeightLimit: number;
  /** Depth of a shopfront 庇, clamped by whatever room the wall has. */
  awningDepth: number;
  /** Height of the 看板 band above a shopfront. */
  signBandHeight: number;
  minFloorArea: number;
  /**
   * Build the outline from the buildable area itself on an irregular lot, rather
   * than composing module rectangles and clipping them.
   */
  conformIrregular: boolean;
  /**
   * Switch to the conforming outline when the largest inscribed rectangle covers
   * less than this fraction of the buildable area. A rectangle scores ~0.95, a
   * trapezoid ~0.8, a triangle ~0.5 — so 0.62 picks out triangles and strong
   * wedges and leaves every ordinary lot on the rectangle path.
   */
  conformFillThreshold: number;
  /** Corners sharper than this get a 隅切り chamfer, degrees. */
  conformCornerAngle: number;
  /** Length of the wall the chamfer leaves behind, metres. */
  conformCornerCut: number;
  /** Probability that an upper-floor bay aligns with the floor below. */
  bayAlignChance: number;
  /** Probability of mirroring the whole building. */
  mirrorChance: number;
  /** Building orientation jitter about the street normal, degrees. */
  orientationJitter: number;
  /**
   * How closely a lot-aligned footprint frame must still agree with the street
   * before it may be used, as |cos| of the angle between them. The footprint
   * fitter searches several frames and keeps whichever holds the largest
   * rectangle, so this is what stops a skewed side boundary from turning the
   * house away from the road it fronts. 0.97 is about 14°.
   */
  frameAlignMin: number;
  eavesMin: number;
  eavesMax: number;
  /**
   * Share of pitched roofs going to each colour family, as relative parts.
   *
   * The mix between these is the most visible single setting in the generator —
   * a town of 赤錆茶 and a town of 銀黒 read as different places from the air —
   * and the right answer is a matter of which suburb you have in mind, so it is
   * exposed rather than tuned. `sampleRoofColor` draws the family from these
   * before it draws a shade, so rejecting a shade for being too pale against its
   * wall can no longer move weight to another family — the numbers hold to
   * within a couple of points, and `test/buildings.test.ts` reports what
   * actually landed. The exception is 瓦, which carries no plain brown: that
   * share redistributes among the families the palette does have.
   */
  roofHueMix: RoofHueMix;
}

export interface PropParams {
  fences: boolean;
  parking: boolean;
  gates: boolean;
  vegetation: boolean;
  laundry: boolean;
  /** 看板・のぼり・自販機 on the shopping streets, and the industrial yard clutter. */
  signage: boolean;
  /** Fraction of house lots that get a parked car. */
  carChance: number;
  /** Fraction of house lots that get a carport roof. */
  carportChance: number;
  /** Fraction of balconies with laundry out. */
  laundryChance: number;
}

export interface RenderParams {
  shadows: boolean;
  shadowMapSize: number;
  shadowExtent: number;
  fog: boolean;
  fogDensity: number;
  /** Hour of day, 0–24, driving sun elevation and azimuth. */
  timeOfDay: number;
  exposure: number;
  textures: boolean;
}

export interface CityParams {
  seed: string;
  terrain: TerrainParams;
  roads: RoadParams;
  landUse: LandUseParams;
  lots: LotParams;
  zoning: ZoningParams;
  platform: PlatformParams;
  buildings: BuildingParams;
  props: PropParams;
  render: RenderParams;
}

export const DEFAULT_GROWTH: GrowthParams = {
  enabled: true,
  steps: 24,
  fullAt: 24,
  spreadExponent: 0.62,
  streetsPerStep: 10,
  candidatesPerStreet: 14,
  coreLotScale: 0.88,
  fringeLotScale: 1.5,
  collectorInterval: 3,
  arterialInterval: 9,
  // 道路構造令 puts a 60 km/h design speed at 5–6%. Residential streets in a
  // Japanese hill suburb routinely run 12–15%, and the 私道 up to a flag lot
  // steeper still.
  maxGradient: { arterial: 0.06, collector: 0.09, local: 0.14, private: 0.18 },
  maxBridgeSpan: 45,
  minRiverCrossAngle: 45,
  fringeVacancy: 0.25,
  profileRelaxIterations: 20,
  slopeWeight: 1.4,
  cutFillWeight: 1.0,
  crossSlopeWeight: 0.5,
  spacingWeight: 0.9,
  reachWeight: 0.7,
  loopBonus: 0.55,
  bridgeCost: 1.1,
};

export const DEFAULT_PARAMS: CityParams = {
  seed: 'sakura-3',
  terrain: {
    enabled: true,
    cell: 4,
    margin: 120,
    relief: 26,
    hillScale: 260,
    hillOctaves: 4,
    tiltGrade: 0.012,
    maxBuildSlope: 0.8,
    river: {
      enabled: true,
      width: 26,
      valleyWidth: 130,
      bedGrade: 0.004,
      waterDepth: 1.1,
      bankMargin: 11,
      meander: 55,
    },
    terrace: {
      count: 2,
      step: 4.0,
      stepVariation: 1.4,
      // One grid cell — see TerraceParams.width.
      width: 4,
      minOffset: 0.22,
      maxOffset: 0.72,
    },
  },
  roads: {
    layout: 'district',
    growth: DEFAULT_GROWTH,
    diagonalCount: 2,
    extent: 320,
    arterialCount: 2,
    arterialWidth: 13,
    collectorWidth: 7,
    collectorSpacing: 170,
    localWidth: 4.8,
    gridSpacingVariation: 0.18,
    deleteFraction: 0.1,
    deadEndFraction: 0.14,
    nodeSnap: 2.5,
    minEdgeLength: 7,
    townAxisJitter: 10,
    tier1BendCount: 2,
    tier1MaxBend: 12,
    tier1MinSpacing: 110,
    minJunctionAngle: 32,
    districtAxisJitter: 10,
    minDistrictArea: 3000,
    minLocalSpacing: 28,
    staggerFraction: 0.3,
    staggerDistance: 7,
    localBendChance: 0.3,
    localBendAngle: 4,
    roadClearance: 2.0,
    perimeterRoad: true,
    perimeterClass: 'local',
    promoteGridLines: false,
  },
  landUse: {
    commercialCoreRadius: 180,
    neighbourhoodRadius: 320,
    commercialShare: 0.16,
    industrialShare: 0.18,
    industrialMinStationDist: 245,
    quasiIndustrialRing: true,
    arterialFrontageWeight: 0.4,
    noiseScale: 260,
    noiseWeight: 0.25,
  },
  lots: {
    minLotArea: 10,
    maxLotArea: 340,
    maxLotAreaMajor: 1500,
    widthMeanMajor: 21,
    depthMeanMajor: 24,
    minFrontage: 1.0,
    depthMean: 12.8,
    depthSigma: 2.5,
    depthMin: 9.5,
    depthMax: 24,
    widthMean: 9.6,
    widthSigma: 2,
    widthMin: 5,
    widthMax: 22,
    cutAngleJitter: 2.5,
    minCoreArea: 520,
    flagLotMinCore: 110,
    privateLaneWidth: 4,
    poleWidth: 2.6,
    flagLotChance: 0.55,
    minInscribedRadius: 0.9,
    gutterWidth: 0.5,
    maxRecursionDepth: 2,
  },
  zoning: {
    stationRadius: 700,
    arterialRadius: 90,
    collectorRadius: 60,
    noiseScale: 220,
    noiseWeight: 0.15,
    mansionMinArea: 400,
    mansionMinFrontage: 14,
    mansionMinUrbanity: 0.55,
    apartMinArea: 180,
    apartMinFrontage: 8,
    apartUrbanityLo: 0.3,
    apartUrbanityHi: 0.75,
    clusterCutChance: 0.25,
    shophouseMinFrontage: 3.6,
    shophouseMaxFrontage: 9,
    shophouseMinUrbanity: 0.5,
    zakkyoMinArea: 200,
    zakkyoMinUrbanity: 0.5,
    konbiniMinArea: 380,
    konbiniMinFrontage: 17,
    konbiniMaxDepthRatio: 1.6,
    konbiniPerDistrict: 1,
    factoryMinArea: 900,
    warehouseMinArea: 1600,
    industrialMinRadius: 9,
  },
  platform: {
    enabled: true,
    plinth: 0.25,
    riserQuantum: 0.15,
    maxRiseAboveStreet: 2.5,
    maxCutBelowStreet: 1.5,
    wallMin: 0.5,
    wallThickness: 0.25,
    wallInset: 0.3,
    batterSlope: 1.5,
    stepRiser: 0.16,
    roadWallMin: 0.6,
  },
  buildings: {
    module: 0.91,
    frontSetback: 0.8,
    sideSetback: 0.5,
    rearSetback: 0.8,
    carPadDepth: 5.0,
    carPadWidth: 3.0,
    footprintFill: 0.93,
    houseCoverage: 0.66,
    houseFar: 1.25,
    houseHeightLimit: 10,
    apartCoverage: 0.7,
    apartFar: 2.1,
    mansionCoverage: 0.7,
    mansionFar: 3.6,
    mansionHeightLimit: 31,
    northSlantBaseLow: 5,
    northSlantBaseMid: 10,
    northSlantSlope: 1.25,
    roadSlantSlope: 1.25,
    floorHeightHouse: 2.9,
    floorHeightApart: 2.75,
    floorHeightMansion: 3.0,
    floorHeightShop: 3.4,
    floorHeightTenant: 3.3,
    floorHeightFactory: 7.6,
    floorHeightWarehouse: 9.0,
    shopCoverage: 0.8,
    shopFar: 3.0,
    zakkyoCoverage: 0.8,
    zakkyoFar: 4.0,
    zakkyoHeightLimit: 31,
    konbiniCoverage: 0.35,
    industrialCoverage: 0.6,
    industrialFar: 2.0,
    industrialHeightLimit: 20,
    awningDepth: 1.0,
    signBandHeight: 0.9,
    minFloorArea: 19,
    conformIrregular: true,
    conformFillThreshold: 0.62,
    conformCornerAngle: 55,
    conformCornerCut: 1.2,
    bayAlignChance: 0.8,
    mirrorChance: 0.5,
    orientationJitter: 1.5,
    frameAlignMin: 0.97,
    eavesMin: 0.45,
    eavesMax: 0.75,
    roofHueMix: { redBrown: 22, navy: 18, grey: 38, brown: 12, green: 10 },
  },
  props: {
    fences: true,
    parking: true,
    gates: true,
    vegetation: true,
    laundry: true,
    signage: true,
    carChance: 0.7,
    carportChance: 0.15,
    laundryChance: 0.45,
  },
  render: {
    shadows: true,
    shadowMapSize: 4096,
    shadowExtent: 260,
    fog: true,
    fogDensity: 0.0009,
    timeOfDay: 10.5,
    exposure: 1.0,
    textures: true,
  },
};

/**
 * Road-layout presets. Switching layout has to move several parameters at once —
 * a grid with the warped layout's 45 m spacing still reads as far too fine — so
 * the presets are kept here and applied as a group.
 */
type RoadPreset = Partial<Omit<RoadParams, 'growth'>> & { growth?: Partial<GrowthParams> };

export const ROAD_LAYOUT_PRESETS: Record<RoadLayout, RoadPreset> = {
  district: {
    // A suburb that grew. Tier-1 is not placed all at once — it is sprouted,
    // extended and promoted over `growth.steps`, so the districts nearest the
    // station were enclosed first and are the smallest and finest.
    growth: { enabled: true },
    gridSpacingVariation: 0.18,
    arterialCount: 2,
    // The diagonals are the main source of districts that disagree with each
    // other: a district with one bounding road at 40° inherits an axis nothing
    // else in the town shares.
    diagonalCount: 2,
    collectorSpacing: 170,
    deleteFraction: 0.1,
    deadEndFraction: 0.14,
    staggerFraction: 0.3,
    localBendChance: 0.3,
    districtAxisJitter: 10,
    promoteGridLines: false,
  },
  grid: {
    // A 区画整理 development is by definition *not* organic: the whole thing was
    // surveyed, laid out and registered at once. So growth is off here, and the
    // one-shot skeleton generator still produces it.
    growth: { enabled: false },
    // One orientation for the whole town, nothing deleted and nothing
    // dead-ending, plus two diagonal through-roads. The block size is not set
    // here — `city/LotModule.ts` derives it from the plot either way, and a
    // 区画整理 grid sized exactly to its plots is what a 区画整理 grid *is*. All
    // that is left to say is that the blocks come out more even than the
    // district layout's.
    gridSpacingVariation: 0.1,
    // No arterials of its own: the hierarchy is assigned to the grid lines
    // instead, so a wide road never slices a block it was not part of.
    arterialCount: 0,
    diagonalCount: 2,
    collectorSpacing: 210,
    deleteFraction: 0,
    deadEndFraction: 0,
    staggerFraction: 0,
    localBendChance: 0,
    districtAxisJitter: 0,
    promoteGridLines: true,
  },
};

/**
 * Apply a layout preset in place, leaving unrelated road parameters alone.
 *
 * `growth` is merged rather than replaced, for two reasons. A blind
 * `Object.assign` would alias one shared `growth` object across every
 * `cloneParams` result — tuning one town would silently tune all of them. And
 * the town's age is something the user sets and then switches layout under; the
 * preset only has an opinion about whether growth runs at all.
 */
export function applyRoadLayout(roads: RoadParams, layout: RoadLayout): RoadParams {
  const { growth, ...rest } = ROAD_LAYOUT_PRESETS[layout];
  Object.assign(roads, rest, { layout });
  if (growth) Object.assign(roads.growth, growth);
  return roads;
}

export function cloneParams(p: CityParams): CityParams {
  return structuredClone(p);
}

export const DEG = Math.PI / 180;
